### ISSUE TITLE
Sensitive Detector Setup

### ISSUE THREAD

**Issue by andresailer** [atolosadelgado/simple_light_detector#1]
https://github.com/atolosadelgado/simple_light_detector/blob/14dc5b539af6aa8d354fbe9627b098ad277e8a93/simple.py#L63

This doesn't work.
The pattern is based on the name of the detector (SimpleDetector), not the type (MYDETECTOR).

See also the output from ddsim
```
DDG4             INFO +++  List of sensitive detectors:
DDG4             INFO +++  SimpleDetector                   type:tracker       --> Sensitive type: ('Geant4TrackerWeightedAction', {'HitPositionCombination': 2, 'CollectSingleDeposits': False})
```

cf.

https://github.com/AIDASoft/DD4hep/blob/a77cd07d3c745c2d4b239e3a48f588dc971955b6/DDG4/python/DDSim/Helper/Action.py#L26
```
  For specific subdetectors specific sensitive detectors can be set based on patterns in the name of the subdetector.
```

**Comment by andresailer** [comment]
Fixing the pattern to `Simple` gives
```
DDSim            INFO Setting up SD for SimpleDetector
DDSim            INFO        replace default action with : Geant4OpticalTrackerAction
```
As part of the output and the error
```
SimpleDetectorHandler ERROR +++++ WRONG!!! Extract. How did we get here?
```

Goes away.

**Comment by atolosadelgado** [comment]
Thanks a lot!! :):)
